In [49]:
#######只保留最近 N 天的数据，仅做最近的数据更新 ###########
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import os

In [50]:
######### 全局变量设置
ndays = 100 ##########设置N的值  n 必须大于34 
testdays = 10 ############### 用来测试的天数
window_size = [3,5,7,10,13,15,20,23,30,33,60]  ######### 股票均线窗口
table_name = 'stocks_dayk_0214'
engine = create_engine('mysql+pymysql://root:root@localhost:3306/stock_db')
dayk_path = '../../dayk0214/'
dayk_files = os.listdir(dayk_path) ###所有日线文件

In [52]:
#################读取w1 与w2##################################
w1 = np.loadtxt("init_w1_30.txt",delimiter=',')
w2 = np.loadtxt("init_w2_30.txt",delimiter=',')
w2 = w2.reshape(-1,1)
#################根据文件内容，初始化w1与w2#####################

######### 设置学习率 
n = 0.5
######### 样本个数 ###########
#print(w2[0:10,:])
print(w1[0:10,0:5])
print(w2[0:10])

[[-0.34568916 -0.39761952 -0.36895151  0.18298564  0.22012321]
 [ 0.6512361   0.30811992  0.70748409  0.7521524   0.69250487]
 [ 0.65033359  0.12667135 -0.40824255  0.01894104  0.52506097]
 [-0.26915649  0.65776578 -0.37557301 -0.43505377 -0.41079509]
 [ 0.60789932 -0.01223864  0.75280235 -0.55486255  0.21063504]
 [ 0.8430385  -0.26934826  0.48541187 -0.36782322 -0.55288571]
 [ 0.31965278 -0.26678083  1.0931587   0.49483582 -0.41324585]
 [-0.18518757  0.4086632   0.03251826  0.21215643  0.95754536]
 [ 1.02946548  0.6753408  -0.76456811  0.56998663 -0.5747292 ]
 [-0.55848459 -0.83179334 -0.60981968 -0.51582332  0.5605415 ]]
[[-1.8091239 ]
 [-0.60163411]
 [ 0.32494214]
 [ 0.50816237]
 [ 0.6530264 ]
 [ 1.16931438]
 [ 1.5630337 ]
 [ 0.60988067]
 [ 0.19571519]
 [ 1.33376621]]


In [53]:
############# 股票信息表，查询股票股本等信息 ################
sql_stock_info = 'select a.code,a.captial from stock_info a '
print(sql_stock_info)
df_stock_info = pd.read_sql_query(sql_stock_info,engine)
print('--------------------done--------------------------')

select a.code,a.captial from stock_info a 
--------------------done--------------------------


In [54]:
se_stock_info = pd.Series(df_stock_info['captial'].values,index=df_stock_info['code'])

In [55]:
def sigmond(x):
    return 1/(1+np.exp(-x))

def reLu(x):
    return (np.abs(x)+x) / 2.0

def d_reLu(x):
    x[x<=0] = 0
    x[x>1] = 1
    return x

def softmax(x):
    x_row_max = x.max(axis=1).reshape(x.shape[0],1)
    x = x - x_row_max
    x_exp = np.exp(x)
    x_row_exp_sum = x_exp.sum(axis=1).reshape(x.shape[0],1)
    x_softmax = x_exp / x_row_exp_sum
    return x_softmax

def softmax_vector(x):
    x_exp = np.exp(x-x.max())
    return x_exp / x_exp.sum()

######### m 为样本个数 ###############
def J_sigmond(h,y,m):
    J = -y*np.log(h) - (1-y)*np.log(1-h)
    return J.sum() / m

In [56]:
################# 多空交叉函数 ##############
def cross_np(var1,var2):
    np_duo_kong = np.zeros(len(var1))
    for i in range(1,len(var1)):
        if var1[i-1]<var2[i-1] and var1[i] > var2[i] :
            np_duo_kong[i]=2
        elif var1[i-1]>var2[i-1] and var1[i]<var2[i] :
            np_duo_kong[i]=-1
        else:
            np_duo_kong[i]=0
    return np_duo_kong

In [61]:
def flag_train_data (code,duokong,index,date,df_dayk):
    i = 0
    index_count = len(date)
    #file = open('stock_data_lable_normal_30.txt','a+')
    data_count = 0
    lab_count = 0
    while(i < index_count -2 ):
        #print('-------- duokong ---------',duokong[i ],date[i])
        if duokong[i] == 2:   ##### 如果出现了  多
            
            #### 判断接下来 n 天，有没有出现 空
            start_index = index[i ] ##当前出现 多的 行号
            end_index = index[i +1] ##下一次出现空的行号
            #print('----间隔天数----',end_index - start_index +1)
            if end_index - start_index > 5 : #### 连续 6天 没有 空
                csv_df = df_dayk.loc[start_index:start_index+5,['open','close','high','low','rise','exchange','ma5','ma10','ma20','ma30','ma60']]
                csv_df_u = df_dayk.loc[start_index:start_index+5,['open','close','high','low','rise','exchange','ma5','ma10','ma20','ma30','ma60']]
                #print(csv_df)
                
                csv_df_u['open'] = (csv_df_u['open'] - csv_df_u['open'].mean()) / csv_df_u['open'].std()
                csv_df_u['close'] = (csv_df_u['close'] - csv_df_u['close'].mean()) / csv_df_u['close'].std()
                csv_df_u['high'] = (csv_df_u['high'] - csv_df_u['high'].mean()) / csv_df_u['high'].std()
                csv_df_u['low'] = (csv_df_u['low'] - csv_df_u['low'].mean()) / csv_df_u['low'].std()
                csv_df_u['rise'] = (csv_df_u['rise'] - csv_df_u['rise'].mean()) / csv_df_u['rise'].std()
                csv_df_u['exchange'] = (csv_df_u['exchange'] - csv_df_u['exchange'].mean()) / csv_df_u['exchange'].std()
                csv_df_u['ma5'] = (csv_df_u['ma5'] - csv_df_u['ma5'].mean()) / csv_df_u['ma5'].std()
                csv_df_u['ma10'] = (csv_df_u['ma10'] - csv_df_u['ma10'].mean()) / csv_df_u['ma10'].std()
                csv_df_u['ma20'] = (csv_df_u['ma20'] - csv_df_u['ma20'].mean()) / csv_df_u['ma20'].std()
                csv_df_u['ma30'] = (csv_df_u['ma30'] - csv_df_u['ma30'].mean()) / csv_df_u['ma30'].std()
                csv_df_u['ma60'] = (csv_df_u['ma60'] - csv_df_u['ma60'].mean()) / csv_df_u['ma60'].std()
                #csv_df_u.to_csv('stock_data_normal_u_30.csv',mode = 'a',index=False,header=None,float_format='%.5f')
                csv_np_u = csv_df_u.values
                csv_np_u = csv_np_u.reshape(-1,66)
                csv_np_u = np.insert(csv_np_u,0,1,axis=1)
                print(csv_np_u.shape)
                nn_test(code,date[i],csv_np_u)
                '''
                csv_df['open'] = (csv_df['open'] - csv_df['open'].min()) / (csv_df['open'].max() - csv_df['open'].min())
                csv_df['close'] = (csv_df['close'] - csv_df['close'].min()) / (csv_df['close'].max() - csv_df['close'].min())
                csv_df['high'] = (csv_df['high'] - csv_df['high'].min()) / (csv_df['high'].max() - csv_df['high'].min())
                csv_df['low'] = (csv_df['low'] - csv_df['low'].min()) / (csv_df['low'].max() - csv_df['low'].min())
                csv_df['rise'] = (csv_df['rise'] - csv_df['rise'].min()) / (csv_df['rise'].max() - csv_df['rise'].min())
                csv_df['exchange'] = (csv_df['exchange'] - csv_df['exchange'].min()) / (csv_df['exchange'].max() - csv_df['exchange'].min())
                csv_df['ma5'] = (csv_df['ma5'] - csv_df['ma5'].min()) / (csv_df['ma5'].max() - csv_df['ma5'].min())
                csv_df['ma10'] = (csv_df['ma10'] - csv_df['ma10'].min()) / (csv_df['ma10'].max() - csv_df['ma10'].min())
                csv_df['ma20'] = (csv_df['ma20'] - csv_df['ma20'].min()) / (csv_df['ma20'].max() - csv_df['ma20'].min())
                csv_df['ma30'] = (csv_df['ma30'] - csv_df['ma30'].min()) / (csv_df['ma30'].max() - csv_df['ma30'].min())
                csv_df['ma60'] = (csv_df['ma60'] - csv_df['ma60'].min()) / (csv_df['ma60'].max() - csv_df['ma60'].min())  
                '''
                #print(csv_df)
                #csv_df.to_csv('stock_data_normal_30.csv',mode = 'a',index=False,header=None,float_format='%.5f')
                #df_dayk.loc[start_index:start_index+5].to_csv('stock_data.csv',mode = 'a',index=False,header=None)
                
        i = i+1
    #file.close()
    
    

In [62]:
def nn_test(code,date,x_test_data):
    
    hid_input = np.matmul(x_test_data,w1)
    hid_output = np.tanh(hid_input)
    hid_output = np.insert(hid_output,0,1,axis=0)
    hpfs_input = np.matmul(hid_output,w2)
    hpfs_output = sigmond(hpfs_input)
    print(code,date,hpfs_output)

In [63]:
### 入库所有通达信 日线文件
### DELETE from stocks_dayk where LENGTH(date)>8;
for file in dayk_files:
    #print(file)
    dayk_df = pd.read_csv(dayk_path+file,skiprows=[0,1],sep=';',encoding='ISO-8859-1',header=None)
    dayk_df.drop([len(dayk_df)-1],inplace=True)
    dayk_df.rename(columns={0:'date',1:'open',2:'high',3:'low',4:'close',5:'vol',6:'money'},inplace=True)
    #print('-----',dayk_df.columns)
    dayk_df['code'] = file[:-4]
    try:
        captial = float(se_stock_info[file[:-4]])
    except:
        continue
    #print(captial)
    days_count = dayk_df.shape[0]  #### 天数
    if days_count>ndays and days_count > 34:
        dayk_df['duokong']=pd.DataFrame(np.zeros(days_count))
        dayk_df = dayk_df.sort_values(by='date',ascending=True)
        #dayk_df = dayk_df.iloc[days_count - ndays:days_count,:]
        max_in_21 = dayk_df['high'].rolling(21).max()
        low_in_21 = dayk_df['low'].rolling(21).min()
        max_in_6 = dayk_df['high'].rolling(6).max()
        low_in_6 = dayk_df['low'].rolling(6).min()
        var1 = 100 - 90*(max_in_21 - dayk_df['close'])/(max_in_21 - low_in_21)
        var2 = 100 - (100*(max_in_6 - dayk_df['close'])/(max_in_6 - low_in_6)).rolling(34).mean()
        var3 = var2.rolling(6).mean()
        dayk_df['duokong'] = pd.DataFrame(cross_np(var1.values,var3.values))
        #dayk_df['rise'] = pd.DataFrame(np.zeros(dayk_df.shape[0]))
        dayk_df['rise'] = (dayk_df['close']-dayk_df['close'].shift(1))/dayk_df['close'].shift(1)
        dayk_df['rise'] = dayk_df['rise'].round(5)
        #print(type(dayk_df[5]))
        #print(type(captial))
        dayk_df['exchange'] = dayk_df['vol']/captial
        dayk_df['exchange'] = dayk_df['exchange']/100000000
        dayk_df['exchange'] = dayk_df['exchange'].round(6)
        #print(dayk_df)
        for i in window_size:
            dayk_df['ma'+str(i)] = dayk_df['close'].rolling(i).mean().round(3)
        dayk_df_insert = dayk_df.iloc[days_count - testdays:days_count,:]
        df_duo = dayk_df_insert[(dayk_df_insert.duokong==2)|(dayk_df_insert.duokong==-1)]
        df_duo_index = df_duo.index.tolist()
        if df_duo_index[df_duo_index.shape[0] - 1] == 2 :
            
            flag_train_data(file[:-4],df_duo['duokong'].values,df_duo_index,df_duo['date'].values,dayk_df_insert)
        #dayk_df_insert.to_sql(table_name,engine,index=False,if_exists='append')
        #print(dayk_df.head(5))
        #print(dayk_df.tail(20))
        #print('finish insert ',file)
print('-------------dataframe to sql is awesome---------------')

(1, 67)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 201 is different from 200)